**Pandas Library**

Pandas is a Python library used for data analysis and data manipulation.
It helps in reading datasets, cleaning data, handling missing values, and preparing data for Machine Learning models.
Pandas mainly works with tables of data called DataFrames.

**Important Pandas Data Structures**

**Series:** A one-dimensional labeled array, like a single column of a table.

**DataFrame:** A two-dimensional table consisting of rows and columns.
Most ML datasets are handled using DataFrames.

**Importing Pandas**

In [90]:
import pandas as pd

**Creating a DataFrame**

**Creating DataFrame from Dictionary:** Data is stored in tabular form.
This method creates a DataFrame using key–value pairs, where keys become column names and values become column data.

In [91]:
dict1 = {
    "Cars": ["BMW", "Volvo", "Tata", "Ford"],
    "Sales": ["6", "8", "4", "16"]
}

df1 = pd.DataFrame(dict1)
print(df1)
df1

    Cars Sales
0    BMW     6
1  Volvo     8
2   Tata     4
3   Ford    16

    Cars Sales
0    BMW     6
1  Volvo     8
2   Tata     4
3   Ford    16

**Viewing Data**

**Head Method:** Displays first 5 rows by default.

In [92]:
df1.head()

    Cars Sales
0    BMW     6
1  Volvo     8
2   Tata     4
3   Ford    16

**Tail Method:** Displays last 5 rows by default.

In [93]:
df1.tail()

    Cars Sales
0    BMW     6
1  Volvo     8
2   Tata     4
3   Ford    16

**Head with Specific Rows**

In [94]:
df1.head(2)

    Cars Sales
0    BMW     6
1  Volvo     8

**Tail with Specific Rows**

In [95]:
df1.tail(1)

   Cars Sales
3  Ford    16

**Accessing Rows**

**loc Method:** Access rows using row labels.

In [96]:
df1.loc[0] # loc - location

Cars     BMW
Sales      6
Name: 0, dtype: object

**iloc Method:** Access rows using index position.

In [97]:
df1.iloc[2] # i - index

Cars     Tata
Sales       4
Name: 2, dtype: object

**Accessing Multiple Rows**

In [98]:
df1.iloc[[0, 2]] # 0th & 2nd records

   Cars Sales
0   BMW     6
2  Tata     4

In [99]:
df1.iloc[[0, 1, 3]]

    Cars Sales
0    BMW     6
1  Volvo     8
3   Ford    16

**Accessing Columns**

**Column Names:** Returns the list of column names present in the DataFrame.

In [100]:
df1.columns

Index(['Cars', 'Sales'], dtype='object')

**Single Column**

In [101]:
df1["Sales"]

0     6
1     8
2     4
3    16
Name: Sales, dtype: object

**Multiple Columns**

In [102]:
df1[["Cars", "Sales"]]

    Cars Sales
0    BMW     6
1  Volvo     8
2   Tata     4
3   Ford    16

**Reading External Files (Very Important for ML)**

**Reading CSV File:** CSV is the most commonly used dataset format in ML.

In [103]:
iris_data = pd.read_csv("/content/drive/MyDrive/Datasets For ML/Iris.csv")

In [132]:
iris_data.head(2)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1              5           3.5            1.4           0.2  Iris-setosa
1   2              4           3.0            1.4           0.2  Iris-setosa

**Reading Excel File:** Used to load datasets stored in Excel format into a DataFrame.

In [105]:
iris_xlsx = pd.read_excel("/content/drive/MyDrive/Datasets For ML/iris.xlsx")

In [133]:
iris_xlsx.head(2)

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa

**Dataset Information and Statistics**

**Describe Method:** Gives statistical summary of numerical columns.

In [107]:
iris_data.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

**Working with Datasets from Google Drive (Colab)**

**Mounting Google Drive:** Google Drive is mounted to access datasets stored in Drive.

In [108]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

**Setting Dataset Path:** Specify the exact file path of the dataset in Drive.

In [109]:
import pandas as pd
import numpy as np

file_path = '/content/drive/My Drive/Datasets For ML/Iris.csv'

**Reading Dataset from Drive:** Loads the dataset from Google Drive into a Pandas DataFrame for analysis.

In [134]:
iris_data = pd.read_csv(file_path)
iris_data.head(2)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa

**Viewing Dataset**

**Head of Dataset:** Used to quickly inspect the contents of the dataset.

In [111]:
iris_data.head(1)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa

**Tail of Dataset**

In [112]:
iris_data.tail(2)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

**Checking Dataset Structure**

**Shape of Dataset:** Shows number of rows and columns. This step helps us understand the size, columns, and data types of the dataset before processing it for Machine Learning

In [113]:
iris_data.shape

(150, 6)

**Dataset Info:** Displays column names, data types, and null values.

In [114]:
iris_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

**Checking Column Names**

In [115]:
iris_data.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

**Handling Missing Values (Demonstration Purpose)**

**Note:** The Iris dataset does not contain missing values.
To understand missing value handling, some values are intentionally replaced with NaN.

**Creating Missing Values Artificially**

In [116]:
iris_missing = iris_data.copy()

iris_missing.iloc[0, 0] = np.nan
iris_missing.iloc[4, 2] = np.nan
iris_missing.iloc[147, 3] = np.nan

iris_missing.head()

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0  NaN            5.1           3.5            1.4           0.2  Iris-setosa
1  2.0            4.9           3.0            1.4           0.2  Iris-setosa
2  3.0            4.7           3.2            1.3           0.2  Iris-setosa
3  4.0            4.6           3.1            1.5           0.2  Iris-setosa
4  5.0            5.0           NaN            1.4           0.2  Iris-setosa

**Handling Missing Values (Very Important in ML)**

**Checking Missing Values:** Counts missing values in each column.

In [117]:
iris_missing.isnull().sum()

Id               1
SepalLengthCm    0
SepalWidthCm     1
PetalLengthCm    1
PetalWidthCm     0
Species          0
dtype: int64

**Dropping Missing Values:** Removes rows containing missing data.

In [118]:
iris_dropped = iris_missing.dropna()
iris_dropped.head()

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1  2.0            4.9           3.0            1.4           0.2  Iris-setosa
2  3.0            4.7           3.2            1.3           0.2  Iris-setosa
3  4.0            4.6           3.1            1.5           0.2  Iris-setosa
5  6.0            5.4           3.9            1.7           0.4  Iris-setosa
6  7.0            4.6           3.4            1.4           0.3  Iris-setosa

**Filling Missing Values:** Replaces missing values with 0.

In [119]:
iris_filled = iris_missing.fillna(0)
iris_filled.head()

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0  0.0            5.1           3.5            1.4           0.2  Iris-setosa
1  2.0            4.9           3.0            1.4           0.2  Iris-setosa
2  3.0            4.7           3.2            1.3           0.2  Iris-setosa
3  4.0            4.6           3.1            1.5           0.2  Iris-setosa
4  5.0            5.0           0.0            1.4           0.2  Iris-setosa

**Filling Missing Values with Mean (Better for ML)**

In [120]:
iris_mean_filled = iris_missing.fillna(iris_missing.mean(numeric_only=True))
iris_mean_filled.head()

     Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0  76.0            5.1      3.500000            1.4           0.2  Iris-setosa
1   2.0            4.9      3.000000            1.4           0.2  Iris-setosa
2   3.0            4.7      3.200000            1.3           0.2  Iris-setosa
3   4.0            4.6      3.100000            1.5           0.2  Iris-setosa
4   5.0            5.0      3.050336            1.4           0.2  Iris-setosa

**Selecting Data for Machine Learning**

**Selecting Feature Columns:** In ML, datasets are split into features (inputs) and target (output). All columns except the last one.

In [121]:
X = iris_data.iloc[:, :-1]
X.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2
3   4            4.6           3.1            1.5           0.2
4   5            5.0           3.6            1.4           0.2

**Selecting Target Column:** The target column contains the output labels that the model learns to predict. Last column of the dataset.

In [122]:
y = iris_data.iloc[:, -1]
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

**Converting Pandas DataFrame to NumPy Array**

In [123]:
numpy_array = iris_data.to_numpy()
print("NumPy array shape:", numpy_array.shape)
print("First 5 rows:\n", numpy_array[:5])

NumPy array shape: (150, 6)
First 5 rows:
 [[1 5.1 3.5 1.4 0.2 'Iris-setosa']
 [2 4.9 3.0 1.4 0.2 'Iris-setosa']
 [3 4.7 3.2 1.3 0.2 'Iris-setosa']
 [4 4.6 3.1 1.5 0.2 'Iris-setosa']
 [5 5.0 3.6 1.4 0.2 'Iris-setosa']]

**Checking Correlation:** Shows relationship between numeriacl features.
Used for feature selection in ML.

In [124]:
iris_numeric = iris_data.select_dtypes(include=[np.number])
iris_numeric.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2
3   4            4.6           3.1            1.5           0.2
4   5            5.0           3.6            1.4           0.2

**Checking Correlation Matrix**

*   Values close to +1 indicate strong positive relationship

*   Values close to -1 indicate strong negative relationship

*   Values near 0 indicate weak or no relationship

In [125]:
iris_corr = iris_numeric.corr()
iris_corr

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
Id,1.000000,0.716676,-0.397729,0.882747,0.899759
SepalLengthCm,0.716676,1.000000,-0.109369,0.871754,0.817954
SepalWidthCm,-0.397729,-0.109369,1.000000,-0.420516,-0.356544
PetalLengthCm,0.882747,0.871754,-0.420516,1.000000,0.962757
PetalWidthCm,0.899759,0.817954,-0.356544,0.962757,1.000000

**Common Observations in Iris Dataset**

*   Petal length and petal width are highly correlated

*   Sepal length has moderate correlation with petal features

*   Sepal width shows weak correlation


**Why Correlation Matters in ML**

*   Removes redundant features

*   Simplifies model training

*   Improves model performance

*   Reduces overfitting

**Additional Important Pandas Methods**

**Checking Value Counts:** Shows the frequency of each unique category in a column.
Used to understand class distribution in classification problems.

In [126]:
iris_data["Species"].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

**Checking Unique Values:** Displays all distinct categories present in a column.
Helps identify the number of classes in the dataset.

In [127]:
iris_data["Species"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

**Sorting Dataset:** Arranges the dataset based on values of a numerical column.
Useful for analysis and data inspection.

In [128]:
iris_data.sort_values(by="PetalLengthCm").head()

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
22  23            4.6           3.6            1.0           0.2  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
35  36            5.0           3.2            1.2           0.2  Iris-setosa
16  17            5.4           3.9            1.3           0.4  Iris-setosa

**Changing Data Type:** Converts a column from one data type to another.
Important for memory optimization and ML compatibility.

In [129]:
iris_data["SepalLengthCm"] = iris_data["SepalLengthCm"].astype(int)
iris_data.dtypes

Id                 int64
SepalLengthCm      int64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

**Random Sampling:** Selects random rows from the dataset.
Used for quick checks and creating sample datasets.

In [130]:
iris_data.sample(2)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
60,61,5,2.0,3.5,1.0,Iris-versicolor
122,123,7,2.8,6.7,2.0,Iris-virginica

**Pivot Table Analysis:** Summarizes numerical values based on categorical columns.
Used for grouped statistical analysis.

In [131]:
pd.pivot_table(
    iris_data,
    values=["SepalLengthCm", "PetalLengthCm"],
    index="Species",
    aggfunc="mean"
)

                 PetalLengthCm  SepalLengthCm
Species
Iris-setosa              1.464           4.60
Iris-versicolor          4.260           5.48
Iris-virginica           5.552           6.08